version: '3.8'

services:
  db:
    image: postgres
    container_name: room25
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
